export const GET_USER_DATA = 'get_user_data'
export const SHOW_USER_DATA = 'show_user_data'
export const SET_LOCATION_LANG = 'set_location_lang'
export const SHOW_SHORTLIST = 'show_shortlist'
export const LOAD_PROFILE = 'load_profile'
export const ADD_TO_SHORTLIST_IN_CLIENT = 'add_to_short_list_in_client'
